'use client'

import { Inter } from 'next/font/google'
import './globals.css'
import TopNavbar from "@/app/components/top-navbar";
import { AuthContextProvider} from "@/app/context/auth-context";

const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AuthContextProvider>
        <TopNavbar />
        {children}
      </AuthContextProvider>
      </body>
    </html>
  )
}
